spring.application.name=mysawit-delivery
# DB Configuration - Menggunakan nilai default jika variabel environment kosong
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5435/mysawit_delivery}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
# Hibernate & Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true
spring.flyway.baseline-on-migrate=true
# Auth Service - Pastikan ini sesuai dengan yang dipanggil di @Value Java
api.auth-service.url=${AUTH_SERVICE_URL:http://localhost:8080/api/users}
# Frontend CORS
app.cors.allowed-origins=${FRONTEND_URL:http://localhost:3000}
# Server Port (Opsional, pastikan tidak bentrok)
server.port=8082
plantation.service.url=http://localhost:8081
plantation.service.admin-token=Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5MjM4ZmJjMi1kOTE5LTRhM2MtODQ3Ni1iNGM5ODMzYmMzODAiLCJlbWFpbCI6ImFkbWluQG15c2F3aXQuY29tIiwicm9sZSI6IkFETUlOIiwidXNlcm5hbWUiOiJBZG1pbiIsIm5hbWEiOiJBZG1pbiIsImlhdCI6MTc3OTI3MDQ3NywiZXhwIjoxNzc5Mjc0MDc3fQ.tD5LMDGt7pKTf0EHZw6d8y51aRArhENQuudvUSKrprA