# Panggil database yang ada di laptopmu
spring.datasource.url=jdbc:postgresql://localhost:5435/mysawit_delivery
spring.datasource.username=postgres
spring.datasource.password=postgres
# URL Modul User di laptop temanmu
#api.user-service.mandor-url=http://localhost:8081/users/mandor/search?name=
# Biarkan Frontend lokal mengakses
app.cors.allowed-origins=http://localhost:3000
# Tampilkan log SQL biar gampang ngecek query
spring.jpa.show-sql=true