spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
# URL Modul User yang sudah di-deploy di internet
api.auth-service.url=${AUTH_SERVICE_URL:http://localhost:8080/api/users}
# URL Frontend asli (misal Vercel)
app.cors.allowed-origins=${FRONTEND_URL}
spring.jpa.show-sql=false
jwt.secret=${JWT_SECRET}